- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config']

- link:
    ~/bin: bin
    ~/.config/ajour/themes: app/ajour/themes
    ~/.config/ajour/ajour.yml: app/ajour/ajour.yml
    ~/.config/alacritty: app/alacritty
    ~/.config/Dharkael: app/Dharkael
    ~/.config/FreeTube/settings.db: app/FreeTube/settings.db
    ~/.config/lutris: game/lutris
    ~/.config/MangoHud: app/MangoHud
    ~/.local/share/applications/signal-desktop.desktop: app/Signal/signal-desktop.desktop
    ~/.gitconfig: git/gitconfig
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.profile: bash/profile
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.zshrc.orig: zsh/zshrc.orig

- create:
  - ~/Applications
  - ~/Books
  - ~/Projects
  - ~/.themes

- shell:
  - [git submodule sync --recursive, Sync any updated URLs from .gitmodules to .git/config.]
  - [git submodule update --init --recursive, Update submodules from any new URLs.]
  - [sudo apt install zsh, Install zsh shell. CTRL+C to cancel if already installed.]
  - [chsh -s $(which zsh), Make zsh the default shell.]
