- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/bin: bin
    ~/.config/ajour/themes: app/ajour/themes
    ~/.config/ajour/ajour.yml: app/ajour/ajour.yml
    ~/.config/alacritty: app/alacritty
    ~/.config/Dharkael: app/Dharkael
    ~/.config/FreeTube/settings.db: app/FreeTube/settings.db
    ~/.config/lutris: game/lutris
    ~/.config/MangoHud: app/MangoHud
    ~/.config/wesnoth: game/wesnoth/config
    ~/.local/share/applications/signal.desktop: app/Signal/signal.desktop
    ~/.aliases.zsh: zsh/custom/aliases.zsh
    ~/.gitconfig: git/gitconfig
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.private.zsh: zsh/custom/private.zsh
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.zshrc.orig: zsh/zshrc.orig

- create:
  - ~/Applications
  - ~/Books
  - ~/Projects
  - ~/.themes

- shell:
  - [git submodule sync --recursive, Sync any updated URLs from .gitmodules to .git/config]
  - [git submodule update --init --recursive, Update submodules from any new URLs]
  - [chsh -s $(which zsh), Make zsh the default shell]
