#!/bin/bash

# Update the system

sudo apt update && sudo apt upgrade -y

# Install wget and apt-transport-https

sudo apt-get install -y wget apt-transport-https

# Add 32-bit architecture

sudo dpkg --add-architecture i386

# Install Wine dependencies

wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo apt-key add winehq.key
sudo apt-get update
sudo apt-get install --install-recommends winehq-staging

# Add Element repo

sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ default main" | sudo tee /etc/apt/sources.list.d/riot-im.list

# Add Signal repo

wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
sudo mv signal-desktop-keyring.gpg /usr/share/keyrings/
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list

# Add Spotify repo

curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list

# Add GitHub CLI repo

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
sudo apt-add-repository https://cli.github.com/packages

# Add ProtonVPN repo

wget -q -O - https://repo.protonvpn.com/debian/public_key.asc | sudo apt-key add - 
sudo add-apt-repository 'deb https://repo.protonvpn.com/debian unstable main'

# Add Kisak Mesa PPA and pin

sudo add-apt-repository -y ppa:kisak/kisak-mesa
printf "Package: *\nPin: release o=LP-PPA-kisak-kisak-mesa\nPin-Priority: 2000\n" | sudo tee /etc/apt/preferences.d/kisak-mesa

# Update and upgrade packages

sudo apt update && sudo apt upgrade -y

# Install dependencies and utilities
# FFmpeg, PPA purge, Seahorse Nautilus extension, Virtual Camera

sudo apt-get install -y \
ffmpeg \
ppa-purge \
seahorse-nautilus \
v4l2loopback-dkms

# Install APT packages

sudo apt-get install -y \
alacritty \
atom \
audacity \
code \
doncf-editor \
discord \
element-desktop \
emacs \
gamemode \
gh \
github-desktop \
gufw \
htop \
lutris \
multimc \
neofetch \
noisetorch \
obs-studio \
peek \
protonvpn \
rclone \
signal-desktop \
spotify-client \
stacer \
steam \
stow \
streamlink \
syncthing \
timeshift \
thunderbird \
transmission \
veracrypt \
vim \
virtualbox \
vlc

# Install Flatpak packages

flatpak install -y flathub \
uk.co.ibboard.cawbird \
org.gnome.Fractal \
org.gabmus.giara \
org.gimp.GIMP \
org.gnome.Lollypop \
com.mattermost.Desktop \
org.onionshare.OnionShare \
com.github.paolostivanin.OTPClient \
org.remmina.Remmina \
com.github.micahflee.torbrowser-launcher

# Install Proton GE

proton-custom-ge-updater

# Install and run the AppImage daemon

wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimaged-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
chmod +x appimaged-*.AppImage
./appimaged-*.AppImage
