format = """
[](white)\
$os\
$username\
[](bg:pop-blue fg:white)\
$directory\
[](bg:white fg:pop-blue)\
$git_branch\
$git_status\
[](bg:pop-blue fg:white)\
$c\
$dart\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$nim\
$python\
$rlang\
$ruby\
$rust\
$scala\
[](bg:white fg:pop-blue)\
$docker_context\
[ ](fg:white)\
"""

right_format = """
$character\
[](white)\
$time\
[](white)\
"""

add_newline = false

palette = "pop"

[palettes.pop]
pop-blue = "#48B9C7"
white = "#FFFFFF"

[os]
style = "bg:white fg:pop-blue"
disabled = false

[username]
show_always = false
style_user = "bold bg:white fg:pop-blue"
style_root = "bold bg:white fg:pop-blue"
format = '[$user ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R"
style = "bold bg:white fg:pop-blue"
format = '[ $time  ]($style)'

[character]
success_symbol = '[󰸞](bold green)'
error_symbol = '[✗](bold red)'

[directory]
style = "bold bg:pop-blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = " ~"
"Applications" = "󱕷 "
"Books" = " "
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "

[c]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bold bg:white fg:pop-blue"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:white fg:pop-blue"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[gradle]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " " # color: pop-blue (#48B9C7)
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[python]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[rlang]
symbol = "ﳒ "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:pop-blue"
format = '[ $symbol ($version) ]($style)'
